[package]
name = "wt_graphs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.3"
qwt = "0.1.32"
serde = "1.0.204"
vers-vecs = { version = "1.3.1", features = ["serde"] }
